---
swagger: "2.0"
info:
  description: "The REST services for annotation,
  notation, types, HLA, GFE, typing, feature and db releases"
  version: "0.0.7"
  title: "GFE REST Services"
  contact:
    email: "mhalagan@nmdp.org"
  license:
    name: "GNU GENERAL PUBLIC LICENSE"
    url: "https://www.gnu.org/licenses/lgpl.html"
tags:
  - name: "Sequence Notation"
    description: "Return notation by sequence"
  - name: "Sequence Annotation"
    description: "Return annotation by sequence"
  - name: "Features Of Locus"
    description: "Return all features associated with a locus"
  - name: "GFE Type-seq Locus"
    description: "Return HLA and GFE from consensus sequence or GFE notation"
  - name: "GFE From HLA"
    description: "Return GFE from HLA,sequence and locus"
  - name: "KIR By GFE"
    description: "Return Kir response by GFE"
  - name: "DB Releases"
    description: "Return all db releases"
  - name: "DB Releases By Locus"
    description: "Return HLA and GFE by imgt_version and locus"
paths:
  /gfe/{gene}/{locus}:
    post:
      tags:
        - "Sequence Notation"
      operationId: "gfeNotation_post"
      consumes:
        - "application/json"
      parameters:
        - name: "locus"
          in: "path"
          description: "Valid HLA locus"
          required: true
          type: "string"
        - name: "gene"
          in: "path"
          description: "KIR flag for gene"
          required: true
          type: "boolean"
          default: false
        - in: 'body'
          name: 'sequence'
          required: true
          description: 'add the sequence to get the result'
          schema:
            type: 'object'
            required:
              - 'sequence'
            properties:
              sequence:
                type: 'string'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Failed to get the notations for sequence'
      x-swagger-router-controller: "swagger_server.controllers.gfe_notation_controller"

  /gfe/seq/annotate/{gene}/{locus}:
    post:
      tags:
        - "Sequence Annotation"
      operationId: "gfeAnnotation_post"
      consumes:
        - "application/json"
      parameters:
        - name: "locus"
          in: "path"
          description: "Valid HLA locus"
          required: true
          type: "string"
        - name: "gene"
          in: "path"
          description: "KIR flag for gene"
          required: true
          type: "boolean"
        - in: 'body'
          name: 'sequence'
          required: true
          description: 'add the sequence to get the result'
          schema:
            type: 'object'
            required:
              - 'sequence'
            properties:
              sequence:
                type: 'string'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to annotate the sequence"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.gfe_annotation_controller"

  /gfe/features/{locus}:
    get:
      tags:
        - "Features Of Locus"
      operationId: "locusfeature_get"
      produces:
        - "application/json"
      parameters:
        - name: "locus"
          in: "path"
          description: "string containing HLA locus"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to load the features of locus"
      x-swagger-router-controller: "swagger_server.controllers.locus_feature_controller"

  /gfe/typing/hla/{locus}:
    post:
      tags:
        - "GFE Type-seq Locus"
      operationId: "gfeTyping_get"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - name: "locus"
          in: "path"
          description: "Valid HLA locus"
          required: true
          type: "string"
        - name: "imgthla_version"
          in: "query"
          description: "IMGT/HLA DB Version"
          required: false
          type: "string"
          default: "3.31.0"
        - name: "sequence"
          in: "body"
          description: "Consensus sequence"
          required: true
          schema:
            type: 'object'
            required:
              - 'sequence'
            properties:
              sequence:
                type: 'string'
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to generate type sequence"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.gfe_typing_controller"

  /gfe/{locus}/{imgt_version}:
    put:
      tags:
        - "GFE From HLA"
      operationId: "gfecreate_post"
      consumes:
        - "application/json"
      parameters:
        - name: "locus"
          in: "path"
          description: "Valid HLA locus"
          required: true
          type: "string"
        - name: "imgt_version"
          in: "path"
          description: "IMGT/HLA DB Version"
          required: true
          type: "string"
          default: "3.31.0"
        - name: "sequence"
          in: "body"
          description: "Consensus sequence"
          required: true
          schema:
            type: 'object'
            required:
              - 'sequence'
            properties:
              sequence:
                type: 'string'
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to create GFE from HLA sequence and locus"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.gfe_create_controller"

  /gfe/kir/{gfe}:
    get:
      tags:
        - "KIR By GFE"
      operationId: "findkir_get"
      consumes:
        - "application/json"
      parameters:
        - name: "gfe"
          in: "path"
          description: "Valid GFE "
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to create GFE from HLA sequence and locus"
      x-swagger-router-controller: "swagger_server.controllers.find_kir_controller"

  /gfe/locus/{imgt_releases}:
    get:
      tags:
        - "DB Releases"
      operationId: "allreleases_get"
      consumes:
        - "application/json"
      parameters:
        - name: "imgt_releases"
          in: "path"
          description: "Valid imgt_releases "
          required: true
          type: "string"
          default: '3.31.0'
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to load all db releases"
      x-swagger-router-controller: "swagger_server.controllers.all_releases_controller"

  /gfe/{locus}/{imgt_releases}:
    get:
      tags:
        - "DB Releases By Locus"
      operationId: "releases_locus_get"
      consumes:
        - "application/json"
      parameters:
        - name: "imgt_releases"
          in: "path"
          description: "Valid imgt_releases "
          required: true
          type: "string"
          default: '3.36.0'
        - name: "locus"
          in: "path"
          description: "Valid locus"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to get GFE and HLA for the imgt_version and locus"
      x-swagger-router-controller: "swagger_server.controllers.releases_by_locus_controller"




definitions:
  Error:
    type: "object"
    required:
      - "Message"
      - "gfedb_version"
      - "imgtdb_version"
      - "pygfe_version"
    properties:
      Message:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
      log:
        type: "array"
        items:
          type: "string"
      type:
        type: "string"
  Typing:
    type: "object"
    properties:
      seqdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      protdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
      novel_features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
      gfe:
        type: "string"
      hla:
        type: "string"
      closest_gfe:
        type: "string"
      full_gene_accession:
        type: "integer"
      differences:
        type: "integer"
      status:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      hla: "HLA-A*01:01:01:01"
      G: "HLA-A*01:01:01G"
      lg: "HLA-A*01:01g"
      full_gene_accession: 10093
      closest_gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      differences: 10
      sequence_differences:
        - term: "intron"
          rank: 1
          pos: 10
          ref: "A"
          inseq: "G"
      protdiff:
        pos: 4
        location: "ARD"
        ref: "A"
        inseq: "G"
      status: "novel"
      features:
        - accession: 1
          locus: "HLA-A"
          rank: 1
          term: "exon"
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
        - accession: 2
          locus: "HLA-A"
          rank: 1
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
          term: "exon"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"
  Seqdiff:
    type: "object"
    properties:
      term:
        type: "string"
      rank:
        type: "integer"
      location:
        type: "integer"
      ref:
        type: "string"
      inseq:
        type: "string"
    example:
      term: "intron"
      rank: 1
      pos: 10
      ref: "A"
      inseq: "G"
  Feature:
    type: "object"
    properties:
      accession:
        type: "integer"
      rank:
        type: "integer"
      sequence:
        type: "string"
      term:
        type: "string"
    example:
      accession: 1
      locus: "HLA-A"
      rank: 1
      sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      term: "exon"
